- name: Secure Kubernetes Namespace
  hosts: localhost
  tasks:
    - name: Ensure namespace with PodSecurity labels
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: secure-namespace
            labels:
              pod-security.kubernetes.io/enforce: "restricted"
              pod-security.kubernetes.io/enforce-version: "latest"

    - name: Apply Resource Quotas to the namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1  # ResourceQuota
          kind: ResourceQuota
          metadata:
            name: resource-quota
            namespace: secure-namespace
          spec:
            hard:
              pods: "10"
              requests.cpu: "4"
              requests.memory: "8Gi"
              limits.cpu: "8"
              limits.memory: "16Gi"

    - name: Apply LimitRange to enforce pod resource limits
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1  # LimitRange
          kind: LimitRange
          metadata:
            name: limits
            namespace: secure-namespace
          spec:
            limits:
              - default:
                  cpu: "1"
                  memory: "512Mi"
                defaultRequest:
                  cpu: "500m"
                  memory: "256Mi"
                type: Container

    - name: Apply NetworkPolicy to restrict ingress and egress traffic
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: restrict-traffic
            namespace: secure-namespace
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        name: secure-namespace
            egress:
              - to:
                  - namespaceSelector:
                      matchLabels:
                        name: secure-namespace
